# Generated by Django 3.2.7 on 2021-09-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Сabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Помещение')),
                ('buildings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='table.buildings', verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип актива', max_length=40, verbose_name='Объект')),
                ('serial', models.BigIntegerField(error_messages={'unique': 'Поле должно быть уникальным'}, max_length=9, unique=True, verbose_name='инв. номер')),
                ('title', models.CharField(max_length=40, verbose_name='Название актива')),
                ('model', models.CharField(max_length=40, verbose_name='Модель актива')),
                ('ip', models.CharField(max_length=40, verbose_name='Ip адрес')),
                ('mac', models.CharField(max_length=40, verbose_name='Mac адрес')),
                ('note', models.TextField(verbose_name='Примечание')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='table.сabinet', verbose_name='Помещение')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='table.dir', verbose_name='Категория'),
        ),
    ]
