# Generated by Django 3.2.7 on 2021-09-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20210908_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип актива')),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='title',
        ),
        migrations.AlterField(
            model_name='object',
            name='buildings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.buildings', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='table.сabinet', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='object',
            name='dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.dir', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название актива'),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(default=1, help_text='Выберите тип актива', max_length=40, on_delete=django.db.models.deletion.CASCADE, to='table.type', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
