# Generated by Django 3.2.7 on 2021-09-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20210913_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='mac',
            field=models.CharField(help_text='Пример: 4c:4e:35:36:08:c1', max_length=40, verbose_name='Mac адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='serial',
            field=models.BigIntegerField(error_messages={'unique': 'Поле должно быть уникальным'}, help_text='Поле должно быть уникальным', unique=True, verbose_name='инв. номер'),
        ),
    ]
