# Generated by Django 3.2.7 on 2021-09-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип актива')),
            ],
        ),
        migrations.CreateModel(
            name='Сabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Помещение')),
                ('buildings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='table.buildings', verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.BigIntegerField(error_messages={'unique': 'Поле должно быть уникальным'}, help_text='Поле должно быть уникальным', unique=True, verbose_name='инв. номер')),
                ('name', models.CharField(max_length=40, verbose_name='Название актива')),
                ('model', models.CharField(max_length=40, verbose_name='Модель актива')),
                ('ip', models.CharField(max_length=40, verbose_name='Ip адрес')),
                ('mac', models.CharField(help_text='Пример: 4c:4e:35:36:08:c1', max_length=40, verbose_name='Mac адрес')),
                ('note', models.TextField(verbose_name='Примечание')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('buildings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.buildings', verbose_name='Корпус')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='table.сabinet', verbose_name='Помещение')),
                ('dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.dir', verbose_name='Категория')),
                ('type', models.ForeignKey(help_text='Выберите тип актива', max_length=40, on_delete=django.db.models.deletion.CASCADE, to='table.type', verbose_name='Объект')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='table.dir', verbose_name='Категория'),
        ),
    ]
