# Generated by Django 3.2.7 on 2021-09-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210927_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.сabinet', verbose_name='Помещение'),
        ),
    ]
